# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a851311f4a56d60c3878de4ee70c28edbdf8453e5e3b7233cb0c9ea32bf9b38d014fff6045edb596e1d60c59976fe2ffafba61d544bde540820a0f81ef620b8

test:
  secret_key_base: 4ac37e9708a95266c1385731165d92d23b4befad6d2949a19bfc99350acfd30ad3749c7a36a025cf441d3fd35826939ede3ff678eb20f03c695b98b6f052ff61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
